# Copyright 2021 - 2023 Universität Tübingen, DKFZ, EMBL, and Universität zu Köln
# for the German Human Genome-Phenome Archive (GHGA)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

docs_dir: user_docs

# Project information
site_name: GHGA User Documentation
site_description: Public documentation for users of the German Human Genome-Phenome Archive.
site_author: The GHGA Team
site_url: https://docs.ghga.de
docs_dir: user_docs
# Repository
repo_name: GHGA User Documentation
repo_url: https://github.com/ghga-de/docs/
edit_uri: "edit/main/docs/"

# Copyright
copyright: 2023 The GHGA Team

# Theming, Configuration
theme:
  name: material
  logo: logo.svg
  font: false
  palette:
    primary: custom

strict: false
extra_css:
  - css/extra.css

# Plugins
plugins:
  - search
  - git-revision-date-localized
  - include_dir_to_nav

# Additional configuration
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ghga-de
    - icon: fontawesome/brands/mastodon
      link: https://genomic.social/@ghga
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ghga_DE

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.superfences

# Page tree
nav:
  - "Overview": index.md
  - "GHGA Metadata Model":
      - "Overview": metadata/overview.md
      - "Standards": metadata/standards.md
      - metadata/concepts.md
      - metadata/modules.md
      - "Submitter Guide": Submitter_guide/Initial.md
      - "Entities & Attributes": metadata/entities.md
      - "Data Dictionary":
          - "Analysis Module": metadata/data_dictionary/analysis-module.md
          - "Basic Module": metadata/data_dictionary/basic-module.md
          - "Data Use Conditions Module": metadata/data_dictionary/data-use-conditions-module.md
          - "Dataset Module": metadata/data_dictionary/dataset-module.md
          - "Phenotype Module": metadata/data_dictionary/phenotype-module.md
          - "Sample Module": metadata/data_dictionary/sample-module.md
          - "Sequencing Module": metadata/data_dictionary/sequencing-module.md
          - "File Submission": metadata/data_dictionary/file-submission.md
  - "CLI Tools": cli_tools
  - "Data Portal": data_portal
  - "Glossary": glossary/glossary.md
