#!/bin/bash
# install service in dev container

cd /workspace

# Install requirements
pip install --upgrade -r requirements.txt

# install pre-commit hooks to git
pip install --upgrade pre-commit
pre-commit install
